[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build --workspace=apps/web"

[deploy]
startCommand = "npm run start --workspace=apps/web"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
